### ISSUE TITLE
Apollo TODO

### ISSUE THREAD

**Issue by jonpas** [Theseus-Aegis/tac-a3-mods#201]
- [ ] Use `getUnitLoadout`/`setUnitLoadout` (also requires database changes) - includes magazine round count
- [ ] Insignias support
- [ ] Earplugs support
- [ ] ACE3 Medical support
- [ ] Static weapons support (deploying/packing events)
