### ISSUE TITLE
Armory Improvements

### ISSUE THREAD

**Issue by jonpas** [Theseus-Aegis/tac-a3-mods#48]
Priority:
- [x] Quantity defaults to blank instead of 1 or max value when stashing an item with bigger quantity than next - `lbSetCurSel` in `FUNC(dialogControl_amountSelection)` to 0 (= 1) every time #74
- [x] Prevent name and amount from overlapping (substring of the name, full name in a tooltip) #74
- [x] Prevent initialization if the box has no inventory #74
- [x] Prevent multiple people opening Armory at the same time on the same box #76 
- [x] ACE Interaction instead of addAction #74
- [x] Mission module and ACE_Setting to toggle Chronos-enabled version (Yes/No or value type) #74
- [x] Mission module to sync/type in container names #74
- [x] Make a new class with preset Armory #74
- [x] Add Zeus compatibility for Armory Locker object #77 
- [x] Remove leftovers of Chronos enabled checks #78
- [x] Prevent saving weapons with attachments or magazines / uniforms/vests/backpack with contents #79 
- [x] Stringtable all hints #80
- [x] Prevent taking if box is full #81

**Comment by SyMP2005** [comment]
-[ ] Add stash all button

**Comment by jonpas** [comment]
Separating bigger things to a new issue.
